// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5_qEINGfIssms6b5-wEXVsqHKIi7ayOo',
    appId: '1:825389689824:web:e8c51aaf69f613a35c1985',
    messagingSenderId: '825389689824',
    projectId: 'aiglass-a3378',
    authDomain: 'aiglass-a3378.firebaseapp.com',
    storageBucket: 'aiglass-a3378.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9_Kg8YMNsCpeAXpKw-MF5k7YnTDxF67E',
    appId: '1:825389689824:android:bf20a57480e7844b5c1985',
    messagingSenderId: '825389689824',
    projectId: 'aiglass-a3378',
    storageBucket: 'aiglass-a3378.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzqn3MZ0OZApT8jIwgHbDxTm4UB-zzy8Q',
    appId: '1:825389689824:ios:751f7313ad0a02a95c1985',
    messagingSenderId: '825389689824',
    projectId: 'aiglass-a3378',
    storageBucket: 'aiglass-a3378.appspot.com',
    iosClientId: '825389689824-0donc40unu790c6fm6c8ikgu3tjfv2j5.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiGlassV2',
  );
}
